title: "FoggyKitchen OCI Container Engine for Kubernetes with Terraform - LESSON 3 - Creating OKE Enhanced Cluster with OKE Add-Ons."
description: "In this lesson, you will learn to use Terraform to set up OKE Enhanced Cluster with OKE Add-Ons."
stackDescription: "In this lesson, you will learn to use Terraform to set up OKE Enhanced Cluster with OKE Add-Ons."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - fk_oke_addon_map

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - show_advanced

- title: "ADBS Deployment"
  visible: 
      and:
        - show_advanced
  variables:
  - deploy_adbs
  - adbs_database_display_name
  - adbs_database_dbname
  - adbs_admin_password

variables:

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region for your OCI OKE Enhanced Cluster"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment"
    description: "Choose Comparment for your OKE Enhanced Cluster"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  deploy_adbs:
    type: boolean
    title: "Deploy Autonomous Database"
    description: "Choose if you want to deploy Autonomous Database with OKE Add-on Database Operator."
    visible: true
    default: false

  adbs_admin_password:
    title: "Autonomous Database ADMIN User Password"
    description: "Autonomous Database ADMIN User Password"
    type: password
    required: true
    visibile: 
      and:
        - deploy_adbs

  adbs_database_display_name:
    title: "Autonomous Database Display Name"
    description: "Type Autonomous Database Display Name"
    type: string
    visibile: 
      and:
        - deploy_adbs

  adbs_database_dbname:
    title: "Autonomous DBName"
    description: "Type Autonomous Database DBName"
    type: string
    visibile: 
      and:
        - deploy_adbs