title: "FoggyKitchen OCI Container Engine for Kubernetes with Terraform - LESSON 7 - Creating OKE Cluster with OCI Block Volume as Kubernetes PVC"
description: "In this lesson, you will learn to use Terraform to set up OKE Cluster with OCI Block Volume as Kubernetes PVC."
stackDescription: "In this lesson, you will learn to use Terraform to set up OKE Cluster with OCI Block Volume as Kubernetes PVC."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - network_cidrs
  - availablity_domain_name

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - show_advanced

- title: "OKE Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - oke_node_shape

- title: "OKE Deployment"
  visible: 
      and:
        - show_advanced
  variables:
  - number_of_nginx_replicas
  - lb_shape
  - flex_lb_min_shape
  - flex_lb_max_shape
  - use_reserved_public_ip_for_lb
  - lb_nsg
  - lb_listener_port

- title: "Block Volume Configuration"
  visible: 
      and:
        - show_advanced
  variables:  
  - pvc_from_existing_block_volume  
  - block_volume_name
  - block_volume_size
  - fs_type
  - vpus_per_gb

variables:

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region for your OCI OKE Enhanced Cluster"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment"
    description: "Choose Comparment for your OKE Enhanced Cluster"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  number_of_nginx_replicas:
    title: "Number of NGINX Replica"
    description: "Choose number of NGINX replicas deployed on your OKE Enhanced Cluster"
    type: integer
    minimum: 1
    maximum: 365
    multipleOf: 1
    default: 10
    required: true
    visibile: true

  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LoadBalancer Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LoadBalancer Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  lb_listener_port:
    type: number
    required: false
    minimum: 1
    maximum: 65563
    multipleOf: 1
    default: 80
    title: "Load Balancer Listener Port"
    description: "Choose Load Balancer Listener Port."

  use_reserved_public_ip_for_lb:
    type: boolean
    title: "Use Reserved Public IP for OKE Load Balancer?"
    description: "Check if you want to use Reserved Public IP for OKE Load Balancer."
    visible: true
    default: false

  lb_nsg:
    type: boolean
    title: "Use NSG instead of Security List for OKE Load Balancer?"
    description: "Check if you want to use Network Security Group for OKE Load Balancer instead of Security List."
    visible: true
    default: true

  pvc_from_existing_block_volume:
    type: boolean
    title: "PVC from existing block volume?"
    description: "Existing (true) means created by Terraform, in opposite (false) it will be create from with K8S."
    visible: true
    default: true

  block_volume_name:
    type: string
    required: false
    title: "Block Volume Name"
    description: "Choose the name for your Block Volume attached as PVC to OKE."

  block_volume_size:
    type: number
    required: false
    minimum: 1
    maximum: 256
    multipleOf: 1
    default: 50
    title: "What is the size of block volume (GB)?"
    description: "Choose number of GB for the size of the Block Volume attached as PVC to OKE."

  fs_type:
    type: enum
    title: "FileSystem Type"
    description: "Choose FileSystem Type for PVC backed by a block volume."
    default: "ext4"
    required: false
    enum: 
      - "ext4"
      - "ext3"
      - "xfs"

  vpus_per_gb:
    type: enum
    required: false
    visible: true
    title: "VPUs per GB"
    description: "Choose performance level for PVC backed by a block volume - Lower Cost (0), Balanced (10), or Higher Performance (20)."
    default: "0"
    enum:
      - "0"  
      - "10"
      - "20"