title: "FoggyKitchen OCI Container Engine for Kubernetes with Terraform - LESSON 5 - Creating OKE Enhanced Cluster with Autoscaler OKE Add-on."
description: "In this lesson, you will learn to use Terraform to set up OKE Enhanced Cluster with Autoscaler OKE Add-on."
stackDescription: "In this lesson, you will learn to use Terraform to set up OKE Enhanced Cluster with Autoscaler OKE Add-on."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - show_advanced

- title: "OKE Optional Configuraton"
  visible: 
      and:
        - show_advanced
  variables:
  - enable_autoscaler_addon
  - autoscaler_authtype_workload
  - kubernetes_version
  - node_linux_version
  - node_pool_size
  - min_number_of_nodes
  - max_number_of_nodes

variables:

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region for your OCI OKE Enhanced Cluster"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment"
    description: "Choose Comparment for your OKE Enhanced Cluster"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false
    
  enable_autoscaler_addon:
    title: "Enable OKE Cluster Autoscaler Add-on"
    description: "Choose if you want to enable OKE Cluster Autoscaler Add-on"
    type: boolean
    default: true
    required: true
    visible: true

  autoscaler_authtype_workload:
    type: boolean
    title: "Autoscaler AuthType Workload?"
    description: "Choose OCI OKE Autoscaler Add-on AuthType (Workload Principal vs Instance Principal)."
    visible: true
    default: true

  kubernetes_version:
    title: "Kubernetes Version"
    description: "Choose Kubernetes Version for your OKE Enhanced Cluster"
    default: "v1.28.2"
    required: false
    type: enum
    enum: 
      - "v1.28.2"
      - "v1.27.2"
      - "v1.26.7"    

  node_linux_version:
    title: "Kubernetes Nodes OS Version"
    description: "Choose Kubernetes Nodes OS Version"
    default: "8.8"
    required: false
    type: enum
    enum: 
      - "8.8"
      - "8.7"       

  node_pool_size:
    title: "Number of Nodes"
    description: "Choose number of Nodes in your OKE Enhanced Cluster's Nodepools (regular & autoscaler)"
    type: integer
    minimum: 1
    maximum: 365
    multipleOf: 1
    default: 3
    required: true
    visible: true

  min_number_of_nodes:
    title: "Min Number of Nodes"
    description: "Choose minimum number of Nodes in OKE Cluster Autoscaler NodePool"
    type: integer
    minimum: 1
    maximum: 365
    multipleOf: 1
    default: 3
    required: true
    visible: true

  max_number_of_nodes:
    title: "Max Number of Nodes"
    description: "Choose maximum number of Nodes in OKE Cluster Autoscaler NodePool"
    type: integer
    minimum: 1
    maximum: 365
    multipleOf: 1
    default: 10
    required: true
    visible: true